### ISSUE TITLE
Backups failing - 'Timeout' object does not support the context manager protocol

### ISSUE THREAD

**Issue by blacknell** [jcwillox/hass-auto-backup#159]
### The problem

Backups have been running without problem for many months. Since yesterday 12pm they've been failing. I run a partial every 3 hours and then a full daily.

### What version of Auto Backup has the issue?

1.5.0

### What version of Home Assistant are you running?

2024.10.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```python3
2024-11-07 07:03:58.620 ERROR (MainThread) [homeassistant.components.automation.backup_critical] While executing automation automation.backup_critical
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 742, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1795, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/__init__.py", line 193, in async_service_handler
    await auto_backup.async_create_backup(data)
  File "/config/custom_components/auto_backup/__init__.py", line 341, in async_create_backup
    installed_addons = await self._handler.get_addons()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/handlers.py", line 111, in get_addons
    result = await self._get_addons_repositories()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/handlers.py", line 31, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auto_backup/handlers.py", line 82, in send_command
    with async_timeout.timeout(timeout):
TypeError: 'Timeout' object does not support the context manager protocol
```

**Comment by floschibo** [comment]
I have the same behavior:
![image](https://github.com/user-attachments/assets/f020a868-dc52-465d-9525-6502a7270872)

**Comment by Sindar-sudo** [comment]
Exact same issue here, auto backup just isn't working anymore...

**Comment by jcwillox** [comment]
Hmm I see the issue, something's changed with the `async_timeout.timeout` method, odd that my backups haven't stopped working on 2024.10 or 2024.11, also on hassos. Hopefully should be an easy fix by switching to the builtin method in python 3.11.
