### ISSUE TITLE
Backup not downloaded

### ISSUE THREAD

**Issue by tieskuh** [jcwillox/hass-auto-backup#78]
### The problem

Backups are not downloaded to the download_path. I cannot figure out why. The back-up succeeds and the event auto_backup.backup_successful is triggered. Also the backup is stored in the backup folder. It all seems to work but the backup isn't downloaded to the download path.

The strange thing is that it did work in the past. I cannot figure out what changed in the mean time. Maybe an update of HA?

Config:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/115901851/204092180-38d80d4e-282f-4b54-95e2-9e70e4dfc248.png">

Download directory with earlier backups in it (nothing since november 17th)
<img width="494" alt="image" src="https://user-images.githubusercontent.com/115901851/204092211-c6ef7aa6-cef6-48ae-8db2-6144c20fee1c.png">

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

2022.11.4

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2022.11.2

### Anything in the logs that might be useful for us?

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1191, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1170, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1200, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 268, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
2022-11-26 15:09:02.414 DEBUG (MainThread) [custom_components.auto_backup] Creating backup 'Saturday, Nov 26, 2022'
2022-11-26 15:09:02.423 DEBUG (MainThread) [custom_components.auto_backup] Installed addons: [{'name': 'AirSonos', 'slug': 'a0d7b954_airsonos', 'description': 'AirPlay capabilities for your Sonos (and UPnP) devices.', 'advanced': False, 'stage': 'stable', 'version': '3.5.0', 'version_latest': '3.5.0', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'a0d7b954', 'build': False, 'url': 'https://github.com/hassio-addons/addon-airsonos', 'icon': True, 'logo': True}, {'name': 'Spotify Connect', 'slug': 'a0d7b954_spotify', 'description': 'Play Spotify music on your Home Assistant device', 'advanced': False, 'stage': 'stable', 'version': '0.12.2', 'version_latest': '0.12.2', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'a0d7b954', 'build': False, 'url': 'https://github.com/hassio-addons/addon-spotify-connect', 'icon': True, 'logo': True}, {'name': 'Terminal & SSH', 'slug': 'core_ssh', 'description': 'Allow logging in remotely to Home Assistant using SSH', 'advanced': True, 'stage': 'stable', 'version': '9.6.1', 'version_latest': '9.6.1', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'core', 'build': False, 'url': 'https://github.com/home-assistant/hassio-addons/tree/master/ssh', 'icon': True, 'logo': True}, {'name': 'Samba share', 'slug': 'core_samba', 'description': 'Expose Home Assistant folders with SMB/CIFS', 'advanced': False, 'stage': 'stable', 'version': '10.0.0', 'version_latest': '10.0.0', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'core', 'build': False, 'url': 'https://github.com/home-assistant/hassio-addons/tree/master/samba', 'icon': True, 'logo': True}, {'name': 'Duck DNS', 'slug': 'core_duckdns', 'description': "Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support", 'advanced': False, 'stage': 'stable', 'version': '1.15.0', 'version_latest': '1.15.0', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'core', 'build': False, 'url': 'https://github.com/home-assistant/hassio-addons/tree/master/duckdns', 'icon': True, 'logo': True}, {'name': 'Mosquitto broker', 'slug': 'core_mosquitto', 'description': 'An Open Source MQTT broker', 'advanced': False, 'stage': 'stable', 'version': '6.1.3', 'version_latest': '6.1.3', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'core', 'build': False, 'url': 'https://github.com/home-assistant/hassio-addons/tree/master/mosquitto', 'icon': True, 'logo': True}, {'name': 'Studio Code Server', 'slug': 'a0d7b954_vscode', 'description': 'Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.', 'advanced': False, 'stage': 'stable', 'version': '5.4.1', 'version_latest': '5.4.1', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'started', 'repository': 'a0d7b954', 'build': False, 'url': 'https://github.com/hassio-addons/addon-vscode', 'icon': True, 'logo': True}, {'name': 'Rclone Backup', 'slug': '19a172aa_rclone_backup', 'description': 'Automatically sync backup to remote locations using rclone', 'advanced': False, 'stage': 'stable', 'version': '3.0.0', 'version_latest': '3.0.0', 'update_available': False, 'available': True, 'detached': False, 'homeassistant': None, 'state': 'error', 'repository': '19a172aa', 'build': False, 'url': 'https://github.com/jcwillox/hassio-rclone-backup', 'icon': True, 'logo': True}]
2022-11-26 15:09:02.423 DEBUG (MainThread) [custom_components.auto_backup] Excluding; addons: [], folders: ['media']
2022-11-26 15:09:02.424 DEBUG (MainThread) [custom_components.auto_backup] Including (excluded); addons: ['a0d7b954_airsonos', 'a0d7b954_spotify', 'core_ssh', 'core_samba', 'core_duckdns', 'core_mosquitto', 'a0d7b954_vscode', '19a172aa_rclone_backup'], folders: ['share', 'ssl', 'addons/local', 'homeassistant']
2022-11-26 15:09:02.424 DEBUG (MainThread) [custom_components.auto_backup] Creating backup (partial); keep_days: 7.0, timeout: 3600, data: {'name': 'Saturday, Nov 26, 2022', 'addons': ['a0d7b954_airsonos', 'a0d7b954_spotify', 'core_ssh', 'core_samba', 'core_duckdns', 'core_mosquitto', 'a0d7b954_vscode', '19a172aa_rclone_backup'], 'folders': ['share', 'ssl', 'addons/local', 'homeassistant']}
2022-11-26 15:11:35.128 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1191, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1170, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1200, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 268, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
2022-11-26 15:11:47.451 INFO (MainThread) [custom_components.auto_backup] Backup created successfully: 'Saturday, Nov 26, 2022' (0b7165b5)
2022-11-26 15:11:47.525 DEBUG (MainThread) [custom_components.auto_backup] No backups required purging.
2022-11-26 15:11:47.567 ERROR (MainThread) [custom_components.auto_backup.handlers] Failed to download backup '0b7165b5' to '/media/HASS_BACKUP/0b7165b5.tar'
2022-11-26 15:11:47.570 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/auto_backup/handlers.py", line 165, in download_backup
    raise HassioAPIError(
custom_components.auto_backup.handlers.HassioAPIError: Backup download failed. Check the logs for more information.
```

### Additional information

When the download failes, it should raise an error.

**Comment by jimkerry01GH** [comment]
Is this still not working for you?

I recently started using auto backup with Home Assistant OS 2023.10.5 and download_path works.

      download_path:
        - /share/SynologyNAS/Backups

**Comment by tieskuh** [comment]
I don't know. I'm not using Auto Backup anymore. I'll close the issue!
